name: Compile LaTeX
on: 
  push:
    branches:
      - "*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Check textbook.pdf is generated
        run: |
            python scripts/check-textbook.py
  check_includeonly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check
        run: |
          ! grep '\includeonly' main.tex 